# Generated by Django 6.1 on 2026-08-17 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='session',
            new_name='workout_session',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='date',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(default='Default Workout', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
